#! /bin/bash
mkdir -p $1
##cp ../libs/*/*.dat $1

EIGENDIR=`cat eigen_root_dir.txt`

webpagefilename=$1/index.html
#cp header.html $webpagefilename
echo ''  > $webpagefilename
echo '<p><strong>Configuration</strong>'  >> $webpagefilename
echo '<ul>'\
  '<li>' `cat /proc/cpuinfo | grep "model name" | head -n 1`\
  '  (' `uname -m` ')</li>'\
  '<li> compiler: ' `cat compiler_version.txt` '</li>'\
  '<li> eigen2: ' `svn info $EIGENDIR | grep Revision` '</li>'\
  '</ul>' \
  '</p>'  >> $webpagefilename

source mk_mean_script.sh axpy $1 11 2500 100000 250000 > $1/axpy.html
source mk_mean_script.sh axpby $1 11 2500 100000 250000 > $1/axpby.html
source mk_mean_script.sh matrix_vector $1 11 50 300 1000 > $1/matrix_vector.html
source mk_mean_script.sh atv $1 11 50 300 1000 > $1/atv.html
source mk_mean_script.sh matrix_matrix $1 11 100 300 1000 > $1/matrix_matrix.html
source mk_mean_script.sh aat $1 11 100 300 1000 > $1/aat.html
source mk_mean_script.sh ata $1 11 100 300 1000 > $1/ata.html
source mk_mean_script.sh trisolve $1 11 100 300 1000 > $1/trisolve.html
source mk_mean_script.sh cholesky $1 11 100 300 1000 > $1/cholesky.html
source mk_mean_script.sh hessenberg $1 11 100 300 1000 > $1/hessenberg.html
source mk_mean_script.sh tridiagonalization $1 11 100 300 1000 > $1/tridiagonalization.html

## compile the web page ##

#echo `cat footer.html` >> $webpagefilename