#!/bin/sh

# configuration
# You should call this script with USER set as you want, else some default
# will be used
USER=${USER:-'orzel'}

#ulimit -v 1024000

# step 1 : build
mkdir build -p
(cd build && cmake .. && make doc) || { echo "make failed"; exit 1; }

#step 2 : upload
# (the '/' at the end of path is very important, see rsync documentation)
rsync -az --no-p --delete build/doc/html/ $USER@ssh.tuxfamily.org:eigen/eigen.tuxfamily.org-web/htdocs/dox-3.0/ || { echo "upload failed"; exit 1; }

echo "Uploaded successfully"

