#!/bin/sh

# configuration
USER='orzel'

# step 1 : update
hg pull -u || (echo "update failed"; exit 1)

# step 2 : build
# todo if 'build is not there, create one:
#mkdir build
(cd build && cmake .. && make -j3 doc) || (echo "make failed"; exit 1)
#todo: n+1 where n = number of cpus

#step 3 : upload
BRANCH=`hg branch`
if [ $BRANCH == "default" ]
then
    BRANCH='devel'
fi
# (the '/' at the end of path are very important, see rsync documentation)
rsync -az build/doc/html/ $USER@ssh.tuxfamily.org:eigen/eigen.tuxfamily.org-web/htdocs/dox-$BRANCH/ ||  (echo "upload failed"; exit 1)


